src/Entity/Ato.php
<?php

namespace App\Entity;

use App\Repository\AtoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AtoRepository::class)
 */
class Ato
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $product;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $length;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $diameter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Capacity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resistance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filling;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $airflow;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCapacity(): ?string
    {
        return $this->Capacity;
    }

    public function setCapacity(?string $Capacity): self
    {
        $this->Capacity = $Capacity;

        return $this;
    }

    public function getProduct(): ?int
    {
        return $this->product;
    }

    public function setProduct(?int $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getLength(): ?string
    {
        return $this->length;
    }

    public function setLength(?string $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getDiameter(): ?string
    {
        return $this->diameter;
    }

    public function setDiameter(?string $diameter): self
    {
        $this->diameter = $diameter;

        return $this;
    }

    public function getResistance(): ?string
    {
        return $this->resistance;
    }

    public function setResistance(?string $resistance): self
    {
        $this->resistance = $resistance;

        return $this;
    }

    public function getFilling(): ?string
    {
        return $this->filling;
    }

    public function setFilling(?string $filling): self
    {
        $this->filling = $filling;

        return $this;
    }

    public function getAirflow(): ?string
    {
        return $this->airflow;
    }

    public function setAirflow(?string $airflow): self
    {
        $this->airflow = $airflow;

        return $this;
    }
}

src/Entity/Ecig.php
<?php

namespace App\Entity;

use App\Repository\EcigRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EcigRepository::class)
 */
class Ecig
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $product;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $power;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Battery;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $autonomy;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Operation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $width;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $depth;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $matter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $NumberOfBatteries;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $TypeOfBatteries;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $RechargableByUsb;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $rechargingConnectors;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $MaxPower;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $inputVoltage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $outputVoltage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chargingVoltage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chargingCurrent;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $compatibleResistance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?int
    {
        return $this->product;
    }

    public function setProduct(int $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getPower(): ?string
    {
        return $this->power;
    }

    public function setPower(?string $power): self
    {
        $this->power = $power;

        return $this;
    }

    public function getBattery(): ?string
    {
        return $this->Battery;
    }

    public function setBattery(?string $Battery): self
    {
        $this->Battery = $Battery;

        return $this;
    }

    public function getAutonomy(): ?string
    {
        return $this->autonomy;
    }

    public function setAutonomy(?string $autonomy): self
    {
        $this->autonomy = $autonomy;

        return $this;
    }

    public function getOperation(): ?string
    {
        return $this->Operation;
    }

    public function setOperation(?string $Operation): self
    {
        $this->Operation = $Operation;

        return $this;
    }

    public function getHeight(): ?string
    {
        return $this->height;
    }

    public function setHeight(?string $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getWidth(): ?string
    {
        return $this->width;
    }

    public function setWidth(?string $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getDepth(): ?string
    {
        return $this->depth;
    }

    public function setDepth(?string $depth): self
    {
        $this->depth = $depth;

        return $this;
    }

    public function getMatter(): ?string
    {
        return $this->matter;
    }

    public function setMatter(?string $matter): self
    {
        $this->matter = $matter;

        return $this;
    }

    public function getWeight(): ?string
    {
        return $this->weight;
    }

    public function setWeight(?string $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getNumberOfBatteries(): ?string
    {
        return $this->NumberOfBatteries;
    }

    public function setNumberOfBatteries(?string $NumberOfBatteries): self
    {
        $this->NumberOfBatteries = $NumberOfBatteries;

        return $this;
    }

    public function getTypeOfBatteries(): ?string
    {
        return $this->TypeOfBatteries;
    }

    public function setTypeOfBatteries(?string $TypeOfBatteries): self
    {
        $this->TypeOfBatteries = $TypeOfBatteries;

        return $this;
    }

    public function getRechargableByUsb(): ?string
    {
        return $this->RechargableByUsb;
    }

    public function setRechargableByUsb(?string $RechargableByUsb): self
    {
        $this->RechargableByUsb = $RechargableByUsb;

        return $this;
    }

    public function getRechargingConnectors(): ?string
    {
        return $this->rechargingConnectors;
    }

    public function setRechargingConnectors(?string $rechargingConnectors): self
    {
        $this->rechargingConnectors = $rechargingConnectors;

        return $this;
    }

    public function getMaxPower(): ?string
    {
        return $this->MaxPower;
    }

    public function setMaxPower(?string $MaxPower): self
    {
        $this->MaxPower = $MaxPower;

        return $this;
    }

    public function getInputVoltage(): ?string
    {
        return $this->inputVoltage;
    }

    public function setInputVoltage(?string $inputVoltage): self
    {
        $this->inputVoltage = $inputVoltage;

        return $this;
    }

    public function getOutputVoltage(): ?string
    {
        return $this->outputVoltage;
    }

    public function setOutputVoltage(?string $outputVoltage): self
    {
        $this->outputVoltage = $outputVoltage;

        return $this;
    }

    public function getChargingVoltage(): ?string
    {
        return $this->chargingVoltage;
    }

    public function setChargingVoltage(?string $chargingVoltage): self
    {
        $this->chargingVoltage = $chargingVoltage;

        return $this;
    }

    public function getChargingCurrent(): ?string
    {
        return $this->chargingCurrent;
    }

    public function setChargingCurrent(?string $chargingCurrent): self
    {
        $this->chargingCurrent = $chargingCurrent;

        return $this;
    }

    public function getCompatibleResistance(): ?string
    {
        return $this->compatibleResistance;
    }

    public function setCompatibleResistance(?string $compatibleResistance): self
    {
        $this->compatibleResistance = $compatibleResistance;

        return $this;
    }
}

templates/index/contact.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{{form(form)}}
{% endblock %}

templates/index/ecig.html.twig
{% extends 'index/index.html.twig' %}
{# {% block title %}{% endblock %} #}
{% block additional_css %}
    {{ parent() }}
{% endblock %}
{% block body %}
   <header>
        {% block header %}
            {{parent()}}
        {% endblock %}
    </header>
    <section>
        {% form_theme tri with ['form_div_layout.html.twig'] only %}
        {{form_start(tri, {'attr': {'id': 'tri'}}) }}
        {{form_end(tri)}}
        <script>
            $('#tri_option2').change(function()
            {
                $('#tri').submit();
            })
        </script>
        <div class="div_card">
            {% for product in products %}
                {% for ecigProduct in  ecigsProducts %}
                    {% if product.id == ecigProduct.product %}       
                        <div class="card" nb={{loop.index}} style="width:18rem;">
                            {% if product.nouveau == 1%}
                                <span class="badge bg-secondary">New</span>
                            {% endif %}
                            <img src="{{ asset(''~ product.image ~'') }}" class="card-img-top" alt="Symfony!" height=300 width=120/>
                            
                            <div class="card-body">
                                <h5 class="card-title">{{product.name}}</h5>
                                <div class="infossup">
                                    <ul>
                                        <li><span class="gras">Puissance : </span>{{ ecigProduct.power }}</li>
                                        <li><span class="gras">Batterie : </span>{{ ecigProduct.battery }}</li>
                                        <li><span class="gras">Autonomie : </span>{{ ecigProduct.autonomy }}</li>
                                        <li><span class="gras">Fonctionnement : </span>{{ ecigProduct.operation }}</li>
                                        <li><span class="gras">Hauteur : </span>{{ ecigProduct.height }}</li>
                                        <li><span class="gras">Largeur : </span>{{ ecigProduct.width }}</li>
                                        <li><span class="gras">Poid : </span>{{ ecigProduct.depth }}</li>
                                        <li><span class="gras">Mattière : </span>{{ ecigProduct.matter }}</li>
                                        <li><span class="gras">Poid : </span>{{ ecigProduct.weight }}</li>
                                        <li><span class="gras">Type de batterie : </span>{{ ecigProduct.typeOfBatteries }}</li>
                                        <li><span class="gras">Nombre de batteries : </span>{{ ecigProduct.numberOfBatteries }}</li>
                                        <li><span class="gras">Rechargeable par USB : </span>{{ ecigProduct.rechargableByUsb }}</li>
                                        <li><span class="gras">Connection de rechargement : </span>{{ ecigProduct.rechargingConnectors }}</li>
                                        <li><span class="gras">Puissance maximum : </span>{{ ecigProduct.maxPower }}</li>
                                        <li><span class="gras">Voltage d'entré : </span>{{ ecigProduct.inputVoltage }}</li>
                                        <li><span class="gras">Voltage de sortie : </span>{{ ecigProduct.outputVoltage }}</li>
                                        <li><span class="gras">Voltage de charge : </span>{{ ecigProduct.chargingVoltage }}</li>
                                        <li><span class="gras">Ampérage de charge : </span>{{ ecigProduct.chargingCurrent }}</li>
                                        <li><span class="gras">Résistance compatible : </span>{{ ecigProduct.compatibleResistance }}</li>                                              
                                    </ul>
                                </div>
                                {# <p class="card-text">{{product.shortDescription}}</p> #}
                                <p class="price">Prix : {{product.price}} €</p>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{loop.index}}">
                                Voir plus
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal{{loop.index}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Description</h5>
                                                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <ul>
                                                    <li><span class="gras">Puissance : </span>{{ ecigProduct.power }}</li>
                                                    <li><span class="gras">Batterie : </span>{{ ecigProduct.battery }}</li>
                                                    <li><span class="gras">Autonomie : </span>{{ ecigProduct.autonomy }}</li>
                                                    <li><span class="gras">Fonctionnement : </span>{{ ecigProduct.operation }}</li>
                                                    <li><span class="gras">Hauteur : </span>{{ ecigProduct.height }}</li>
                                                    <li><span class="gras">Largeur : </span>{{ ecigProduct.width }}</li>
                                                    <li><span class="gras">Poid : </span>{{ ecigProduct.depth }}</li>
                                                    <li><span class="gras">Mattière : </span>{{ ecigProduct.matter }}</li>
                                                    <li><span class="gras">Poid : </span>{{ ecigProduct.weight }}</li>
                                                    <li><span class="gras">Type de batterie : </span>{{ ecigProduct.typeOfBatteries }}</li>
                                                    <li><span class="gras">Nombre de batteries : </span>{{ ecigProduct.numberOfBatteries }}</li>
                                                    <li><span class="gras">Rechargeable par USB : </span>{{ ecigProduct.rechargableByUsb }}</li>
                                                    <li><span class="gras">Connection de rechargement : </span>{{ ecigProduct.rechargingConnectors }}</li>
                                                    <li><span class="gras">Puissance maximum : </span>{{ ecigProduct.maxPower }}</li>
                                                    <li><span class="gras">Voltage d'entré : </span>{{ ecigProduct.inputVoltage }}</li>
                                                    <li><span class="gras">Voltage de sortie : </span>{{ ecigProduct.outputVoltage }}</li>
                                                    <li><span class="gras">Voltage de charge : </span>{{ ecigProduct.chargingVoltage }}</li>
                                                    <li><span class="gras">Ampérage de charge : </span>{{ ecigProduct.chargingCurrent }}</li>
                                                    <li><span class="gras">Résistance compatible : </span>{{ ecigProduct.compatibleResistance }}</li>                                              
                                                </ul>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/index/ficheTechnique.html.twig
{% extends 'base.html.twig' %}

{# {% block title %}{% endblock %} #}
{% block additional_css %}
    <link rel="stylesheet" href="{{asset('css/ficheTechnique.css')}}">
{% endblock %}
{% block body %}
<div>
    <img src="{{ asset(''~ product.image ~'') }}" id="image{{product.id}}" class="image" alt="Symfony!" width='45%'/>

    <ul>
        <li><span class="gras">Marque : </span>{{ product.brand }}</li>
        <li><span class="gras">Model : </span>{{ product.name }}</li>
        <li><span class="gras">Prix : </span>{{ product.price }} €</li>
        <li><span class="gras">Description : </span>{{ product.description }}</li>
        <li><span class="gras">Notes Dominantes : </span>{{ eliquid.DominantNotes }}</li>
        <li><span class="gras">Type d'arome : </span>{{ eliquid.TypeOfAroma }}</li>
        <li><span class="gras">Ratio PG/VG : </span>{{ eliquid.ratio }}</li>
        <li><span class="gras">Nicotine : </span>{{ eliquid.Nicotine }}</li>
        <li><span class="gras">Capacité : </span>{{ eliquid.Capacity }}</li>
        <li><span class="gras">Origine : </span>{{ eliquid.Origin }}</li>
    </ul>
</div>
  

    
{% endblock %}

templates/index/fullkit.html.twig
{% extends 'index/index.html.twig' %}
{# {% block title %}{% endblock %} #}
{% block additional_css %}
    {{ parent() }}
{% endblock %}
{% block body %}
   <header>
        {% block header %}
            {{parent()}}
        {% endblock %}
    </header>
    <section>
        {% form_theme tri with ['form_div_layout.html.twig'] only %}
        {{form_start(tri, {'attr': {'id': 'tri'}}) }}
        {{form_end(tri)}}
        <script>
            $('#tri_option2').change(function()
            {
                $('#tri').submit();
            })
        </script>
        <div class="div_card">
            {% for product in products %}
                {% for fullkitProduct in  fullkitsProducts %}
                    {% if product.id == fullkitProduct.product %}       
                        <div class="card" nb={{loop.index}} style="width:18rem;">
                            {% if product.nouveau == 1%}
                                <span class="badge bg-secondary">New</span>
                            {% endif %}
                            <img src="{{ asset(''~ product.image ~'') }}" class="card-img-top" alt="Symfony!" height=300 width=120/>
                            
                            <div class="card-body">
                                <h5 class="card-title">{{product.name}}</h5>
                                <h6>{{product.brand}}</h6>
                                <div class="infossup">
                                    <ul>
                                        {# <li><span class="gras">Description :</span>{{ product.description }}</li> #}
                                        <li><span class="gras">Longueur : </span>{{ fullkitProduct.length }}</li>
                                        <li><span class="gras">Diametre : </span>{{ fullkitProduct.diameter }}</li>
                                        <li><span class="gras">Contenance : </span>{{ fullkitProduct.capacity }}</li>
                                        <li><span class="gras">Résistance : </span>{{ fullkitProduct.resistance }}</li>
                                        <li><span class="gras">Remplissage : </span>{{ fullkitProduct.filling }}</li>
                                        <li><span class="gras">Airflow : </span>{{ fullkitProduct.airflow }}</li>
                                        <li><span class="gras">Puissance : </span>{{ fullkitProduct.power }}</li>
                                        <li><span class="gras">Batterie : </span>{{ fullkitProduct.battery }}</li>
                                        <li><span class="gras">Autonomie : </span>{{ fullkitProduct.autonomy }}</li>
                                        <li><span class="gras">Fonctionnement : </span>{{ fullkitProduct.operation }}</li>
                                        <li><span class="gras">Hauteur : </span>{{ fullkitProduct.height }}</li>
                                        <li><span class="gras">Largeur : </span>{{ fullkitProduct.width }}</li>
                                        <li><span class="gras">Poid : </span>{{ fullkitProduct.depth }}</li>
                                        <li><span class="gras">Mattière : </span>{{ fullkitProduct.matter }}</li>
                                        <li><span class="gras">Poid : </span>{{ fullkitProduct.weight }}</li>
                                        <li><span class="gras">Type de batterie : </span>{{ fullkitProduct.typeOfBatteries }}</li>
                                        <li><span class="gras">Nombre de batteries : </span>{{ fullkitProduct.numberOfBatteries }}</li>
                                        <li><span class="gras">Rechargeable par USB : </span>{{ fullkitProduct.rechargableByUsb }}</li>
                                        <li><span class="gras">Connection de rechargement : </span>{{ fullkitProduct.rechargingConnectors }}</li>
                                        <li><span class="gras">Puissance maximum : </span>{{ fullkitProduct.maxPower }}</li>
                                        <li><span class="gras">Voltage d'entré : </span>{{ fullkitProduct.inputVoltage }}</li>
                                        <li><span class="gras">Voltage de sortie : </span>{{ fullkitProduct.outputVoltage }}</li>
                                        <li><span class="gras">Voltage de charge : </span>{{ fullkitProduct.chargingVoltage }}</li>
                                        <li><span class="gras">Ampérage de charge : </span>{{ fullkitProduct.chargingCurrent }}</li>
                                        <li><span class="gras">Résistance compatible : </span>{{ fullkitProduct.compatibleResistance }}</li>
                                    </ul>
                                </div>
                                {# <p class="card-text">{{product.shortDescription}}</p> #}
                                <p class="price">{{product.price}} €</p>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{loop.index}}">
                                Voir plus
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal{{loop.index}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Description</h5>
                                                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <ul>
                                                    {# <li><span class="gras">Description :</span>{{ product.description }}</li> #}
                                                    <li><span class="gras">Longueur : </span>{{ fullkitProduct.length }}</li>
                                                    <li><span class="gras">Diametre : </span>{{ fullkitProduct.diameter }}</li>
                                                    <li><span class="gras">Contenance : </span>{{ fullkitProduct.capacity }}</li>
                                                    <li><span class="gras">Résistance : </span>{{ fullkitProduct.resistance }}</li>
                                                    <li><span class="gras">Remplissage : </span>{{ fullkitProduct.filling }}</li>
                                                    <li><span class="gras">Airflow : </span>{{ fullkitProduct.airflow }}</li>
                                                    <li><span class="gras">Puissance : </span>{{ fullkitProduct.power }}</li>
                                                    <li><span class="gras">Batterie : </span>{{ fullkitProduct.battery }}</li>
                                                    <li><span class="gras">Autonomie : </span>{{ fullkitProduct.autonomy }}</li>
                                                    <li><span class="gras">Fonctionnement : </span>{{ fullkitProduct.operation }}</li>
                                                    <li><span class="gras">Hauteur : </span>{{ fullkitProduct.height }}</li>
                                                    <li><span class="gras">Largeur : </span>{{ fullkitProduct.width }}</li>
                                                    <li><span class="gras">Poid : </span>{{ fullkitProduct.depth }}</li>
                                                    <li><span class="gras">Mattière : </span>{{ fullkitProduct.matter }}</li>
                                                    <li><span class="gras">Poid : </span>{{ fullkitProduct.weight }}</li>
                                                    <li><span class="gras">Type de batterie : </span>{{ fullkitProduct.typeOfBatteries }}</li>
                                                    <li><span class="gras">Nombre de batteries : </span>{{ fullkitProduct.numberOfBatteries }}</li>
                                                    <li><span class="gras">Rechargeable par USB : </span>{{ fullkitProduct.rechargableByUsb }}</li>
                                                    <li><span class="gras">Connection de rechargement : </span>{{ fullkitProduct.rechargingConnectors }}</li>
                                                    <li><span class="gras">Puissance maximum : </span>{{ fullkitProduct.maxPower }}</li>
                                                    <li><span class="gras">Voltage d'entré : </span>{{ fullkitProduct.inputVoltage }}</li>
                                                    <li><span class="gras">Voltage de sortie : </span>{{ fullkitProduct.outputVoltage }}</li>
                                                    <li><span class="gras">Voltage de charge : </span>{{ fullkitProduct.chargingVoltage }}</li>
                                                    <li><span class="gras">Ampérage de charge : </span>{{ fullkitProduct.chargingCurrent }}</li>
                                                    <li><span class="gras">Résistance compatible : </span>{{ fullkitProduct.compatibleResistance }}</li>
                                                </ul>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </div>
    </section>
{% endblock %}